compatibilityVersion: naiscript-1.0
id: 24102197-a316-472b-980f-98f0b39dc837
name: word-counter
version: 1.0.0
createdAt: 1765307235
author: NovelAI Script Build System
description: "A simple word and character counter for your story License: MIT"
memoryLimit: 8
updatedAt: 1766415441
config: []
