import { IconData, SvgNode } from "./types";

const BANNER = "// AUTO-GENERATED by nibs iconsPlugin. Do not edit.";

const MAKE = `const make = (viewBox, build) => (props = {}) => {
  const { size, color, strokeWidth, ...rest } = props;
  return h("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    width: size ?? 16,
    height: size ?? 16,
    viewBox,
    fill: "none",
    stroke: color ?? "currentColor",
    "stroke-width": strokeWidth ?? 2,
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
    ...rest,
  }, ...build());
};`;

function emitNode(node: SvgNode): string {
  const children = node.children?.length
    ? ", " + node.children.map(emitNode).join(", ")
    : "";
  return `h(${JSON.stringify(node.tag)}, ${JSON.stringify(node.attrs)}${children})`;
}

function emitIcon(name: string, data: IconData): string {
  const childExprs = data.children.map(emitNode).join(", ");
  return `export const ${name} = /*#__PURE__*/ make(${JSON.stringify(
    data.viewBox,
  )}, () => [${childExprs}]);`;
}

export function emitModule(iconMap: Map<string, IconData>): string {
  const icons = [...iconMap.entries()]
    .map(([name, data]) => emitIcon(name, data))
    .join("\n");
  return `${BANNER}\n\n${MAKE}\n\n${icons}\n`;
}
