import { writeFile } from "fs/promises";
import { join } from "path";
import { featherProvider } from "../src/plugins/icons/feather-provider";

const HEADER = `// AUTO-GENERATED by scripts/gen-icon-types.ts. Do not edit by hand.
// Regenerate with: npm run gen:icon-types

interface IconProps {
  size?: number;
  color?: string;
  strokeWidth?: number;
  class?: string;
  style?: unknown;
  onClick?: (e: any) => void;
  [key: string]: unknown;
}
type IconComponent = (props?: IconProps) => unknown;
`;

async function main() {
  const icons = await featherProvider.load();
  const names = [...icons.keys()].sort();
  const decls = names.map((n) => `  export const ${n}: IconComponent;`).join("\n");
  const body = `${HEADER}\ndeclare module "nai:icons/feather" {\n${decls}\n}\n`;
  const out = join(__dirname, "..", "assets", "nai-icons.d.ts");
  await writeFile(out, body, "utf-8");
  console.log(`Wrote ${names.length} icon declarations to ${out}`);
}

main();
